global:
  scrape_interval: 5s

scrape_configs:
        - job_name: 'snmp'
          static_configs:
                  - targets: ['INSERT IPs, can insert a list']
          metrics_path: /snmp
          params:
                  module: [if_mib]
          relabel_configs:
                  - source_labels: [__address__]
                    target_label: __param_target
                  - source_labels: [__param_target]
                    target_label: instance
                  - source_labels: []
                    target_label: __address__
                    replacement: 'snmp-exporter:9116'

