global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'snmp1'
    static_configs:
      - targets:
        - 10.0.19.42
        - 10.0.17.42 
          # SNMP device.
          # metrics_path: /snmp
    params:
      module: [if_mib]
      community: [kznstack]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'snmp-exporter:9116'  # The SNMP exporter's real hostname:port

  - job_name: 'snmp'
    static_configs:
      - targets: ['10.0.19.42','10.0.17.42']
    metrics_path: /snmp
    params:
      module: [cisco_wlc]
      community: [kznstack]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: []
        target_label: __address__
        replacement: 'snmp-exporter:9116'
